### ISSUE TITLE
VODLambdaConvert crashes when special characters are in file name

### ISSUE THREAD

**Issue by TimDaub** [aws-samples/aws-media-services-vod-automation#5]
When I upload the following file to my s3 bucket with the name `test&.mp4`, VODLambdaConvert errors with the following message and does not convert the file:

`[ERROR]	2019-05-08T08:28:51.654Z	e6a8b072-9bd2-4e7c-88f1-c6748322697f	Exception: An error occurred (BadRequestException) when calling the CreateJob operation: The user metadata value 's3://<bucketname>/inputs/543dd76f-6385-4878-b7b6-8cb2dd2f3a6f-test%26.mp4' is invalid.`

I'm using the following template: https://github.com/aws-samples/aws-media-services-vod-automation/tree/master/MediaConvert-WorkflowWatchFolderAndNotification

**Comment by morjoan** [comment]
Seems like the issue is actually about having special characters in the user metadata, than the file name itself. Running a job with an ampersand in filename works fine. Since this is a limitation with MediaConvert itself, please feel free to open a support case with AWS Support if you have a support plan or just post on the AWS Support Forums to get this looked into.
